version: '3'
services:
  db:
    image: postgres
    environment:
      - POSTGRES_USER=wp-test
      - POSTGRES_PASSWORD=
    ports:
      - '5432:5432'
    networks:
      - appnetwork
  web:
    build: .
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - .:/mercadoClone
    ports:
      - "3000:3000"
    depends_on:
      - db
      - mailcatcher
    networks:
      - appnetwork 
  mailcatcher:
    image: schickling/mailcatcher
    container_name: mailcatcher
    ports:
      - "1080:1080"
    networks:
      - appnetwork
networks:
  appnetwork:
    driver: bridge
